### ISSUE TITLE
pretrain models

### ISSUE THREAD

**Issue by laserwave** [mrezaei92/TriHorn-Net#1]
HI,

Could you provide pretrained models？

**Comment by mrezaei92** [comment]
> HI,
> 
> Could you provide pretrained models？

Hi,
Thanks for reaching out. You can access the models on my Google Drive at the following link:
https://drive.google.com/drive/folders/1lTNrMKr9WPQmkBaLbnp6v_7zJos3a0Fi?usp=sharing

**Comment by laserwave** [comment]
thank you

**Comment by ArenaGrenade** [comment]
Hi! Seems you have updated the code or models somehow between posting this and now. Could you please share your updated checkpoints as well? Thanks for the great work!
