### ISSUE TITLE
For ICVL dataset, can't find any release of train.pickle file.

### ISSUE THREAD

**Issue by nasif-raihan** [mrezaei92/TriHorn-Net#4]
In the README.md file, there is mentioned of keeping both **_test.pickle_** and **_train.pickle_** in one folder which will serve as the ICVL dataset folder. I can not figure from out where I can download **_train.pickle_** file.

**Comment by mrezaei92** [comment]
Dear @nasif-raihan,

As explained in README.md, you should first download the raw ICVL dataset from the link provided. Then you should Navigate to the folder data/ICVL. Run the following command to get a file named train.pickle:
 python prepareICVL_train.py ICVLpath/Training
